/**
 * Python 잠금 파일 검사(`scripts/python-lock.mjs --check`)의 읽기와 판 비교 규칙.
 *
 * 저장소의 잠금 파일이 `pyproject.toml` 과 맞는지는 `pnpm verify` 와 CI 가 `--check` 로 본다.
 */

import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { describe, expect, it } from 'vitest';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const SCRIPT = path.join(ROOT, 'scripts/python-lock.mjs');

interface PythonLock {
    tomlStringArray(text: string, section: string, key: string): string[];
    parseIn(text: string): string[];
    parsePins(text: string): Map<string, string>;
    satisfies(requirement: string, pins: Map<string, string>): true | string;
}

// 타입 선언이 없는 .mjs 다. 경로를 변수로 만들어 불러오면 타입 검사가 파일 안쪽으로 따라가지 않는다.
const lock = (await import(pathToFileURL(SCRIPT).href)) as PythonLock;

describe('python-lock 읽기', () => {
    const pyproject = [
        '[build-system]',
        'requires = ["hatchling>=1.24"]',
        '',
        '[project]',
        'name = "x"',
        'dependencies = ["requests>=2.33.0", "aiohttp>=3.14.3"]',
        'classifiers = [',
        '    "Programming Language :: Python :: 3",',
        ']',
        '',
        '[project.optional-dependencies]',
        'dev = [',
        "    'pytest>=8',",
        '    "extra[with-bracket]>=1",',
        ']',
    ].join('\n');

    it('pyproject.toml 의 절에서 문자열 배열을 읽는다(여러 줄, 작은따옴표, 따옴표 안의 ] 포함)', () => {
        expect(lock.tomlStringArray(pyproject, 'build-system', 'requires')).toEqual(['hatchling>=1.24']);
        expect(lock.tomlStringArray(pyproject, 'project', 'dependencies')).toEqual(['requests>=2.33.0', 'aiohttp>=3.14.3']);
        expect(lock.tomlStringArray(pyproject, 'project.optional-dependencies', 'dev')).toEqual(['pytest>=8', 'extra[with-bracket]>=1']);
    });

    it('절이나 키가 없으면 던진다. [project] 의 키를 [project.optional-dependencies] 에서 찾지 않는다', () => {
        expect(() => lock.tomlStringArray(pyproject, 'project', 'dev')).toThrow('[project] 에서 dev');
        expect(() => lock.tomlStringArray(pyproject, 'tool.none', 'x')).toThrow('[tool.none]');
    });

    it('.in 에서 주석, 빈 줄, 옵션 줄을 빼고 요구사항만 읽는다', () => {
        expect(lock.parseIn('# 머리 주석\n-c runtime.txt\n-r runtime.in\n\npytest>=8  # 끝 주석\nhatchling>=1.24\n')).toEqual(['pytest>=8', 'hatchling>=1.24']);
    });

    it('.txt 에서 고정한 판을 정규화한 이름으로 읽는다(환경 마커와 해시 줄 무시)', () => {
        const pins = lock.parsePins([
            '# This file was autogenerated by uv via the following command:',
            'Typing_Extensions==4.16.0 ; python_full_version < \'3.13\' \\',
            '    --hash=sha256:' + 'a'.repeat(64),
            '    # via aiohttp',
            'requests==2.34.2 \\',
        ].join('\n'));
        expect([...pins]).toEqual([['typing-extensions', '4.16.0'], ['requests', '2.34.2']]);
    });
});

describe('python-lock 판 비교', () => {
    const pins = new Map([['requests', '2.34.2'], ['pytest', '9.1.1'], ['odd', '1.0rc1']]);

    it('범위를 만족하면 true 다', () => {
        for (const requirement of ['requests>=2.33.0', 'requests>=2.34.2', 'Requests == 2.34.2', 'requests>=2,<3', 'requests!=2.34.1', 'pytest>=8', 'pytest'])
            expect(lock.satisfies(requirement, pins), requirement).toBe(true);
    });

    it('범위를 벗어나거나 고정한 판이 없으면 이유를 돌려준다', () => {
        expect(lock.satisfies('requests>=2.35', pins)).toContain('만족하지 않는다');
        expect(lock.satisfies('requests<2.34.2', pins)).toContain('만족하지 않는다');
        expect(lock.satisfies('hatchling>=1.24', pins)).toContain('고정한 판이 없다');
    });

    it('숫자로만 된 판이 아니거나 모르는 연산자면 통과시키지 않고 알린다', () => {
        expect(lock.satisfies('odd>=1.0', pins)).toContain('비교하지 못한다');
        expect(lock.satisfies('requests==2.*', pins)).toContain('비교하지 못한다');
        expect(lock.satisfies('requests===2.34.2', pins)).toContain('비교하지 못한다');
        expect(lock.satisfies('requests~=2.34', pins)).toContain('비교하지 못한다');
    });
});
