# 이 파일은 scripts/gen-python-abstract.mjs 가 ts/src/spec/toss.json 에서 만든다. 직접 고치지 않는다.
from kr_broker.base.types import Entry


class ImplicitAPI:
    public_post_oauth2_token = publicPostOauth2Token = Entry('oauth2/token', 'public', 'POST', {'cost': 1, 'bucket': 'auth'})
    private_market_get_accounts = privateMarketGetAccounts = Entry('accounts', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'account'})
    private_market_get_exchange_rate = privateMarketGetExchangeRate = Entry('exchange-rate', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'market_info'})
    private_market_get_market_calendar_kr = privateMarketGetMarketCalendarKR = Entry('market-calendar/KR', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'market_info'})
    private_market_get_market_calendar_us = privateMarketGetMarketCalendarUS = Entry('market-calendar/US', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'market_info'})
    private_market_get_prices = privateMarketGetPrices = Entry('prices', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'market_data'})
    private_market_get_orderbook = privateMarketGetOrderbook = Entry('orderbook', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'market_data'})
    private_market_get_candles = privateMarketGetCandles = Entry('candles', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'market_data_chart'})
    private_market_get_trades = privateMarketGetTrades = Entry('trades', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'market_data'})
    private_market_get_price_limits = privateMarketGetPriceLimits = Entry('price-limits', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'market_data'})
    private_market_get_stocks = privateMarketGetStocks = Entry('stocks', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'stock'})
    private_market_get_stocks_all = privateMarketGetStocksAll = Entry('stocks/all', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'stock_all'})
    private_market_get_stocks_symbol_warnings = privateMarketGetStocksSymbolWarnings = Entry('stocks/{symbol}/warnings', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'stock'})
    private_market_get_rankings = privateMarketGetRankings = Entry('rankings', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'ranking'})
    private_market_get_market_indicators_symbol_investor_trading = privateMarketGetMarketIndicatorsSymbolInvestorTrading = Entry('market-indicators/{symbol}/investor-trading', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'market_indicator'})
    private_market_get_market_indicators_prices = privateMarketGetMarketIndicatorsPrices = Entry('market-indicators/prices', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'market_indicator'})
    private_market_get_market_indicators_symbol_candles = privateMarketGetMarketIndicatorsSymbolCandles = Entry('market-indicators/{symbol}/candles', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'market_indicator_chart'})
    private_market_get_stocks_symbol_investor_trading = privateMarketGetStocksSymbolInvestorTrading = Entry('stocks/{symbol}/investor-trading', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'stock_trading_trend'})
    private_market_get_stocks_symbol_program_trades = privateMarketGetStocksSymbolProgramTrades = Entry('stocks/{symbol}/program-trades', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'stock_trading_trend'})
    private_market_get_stocks_symbol_short_selling = privateMarketGetStocksSymbolShortSelling = Entry('stocks/{symbol}/short-selling', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'stock_trading_trend'})
    private_market_get_stocks_symbol_credit_trades = privateMarketGetStocksSymbolCreditTrades = Entry('stocks/{symbol}/credit-trades', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'stock_trading_trend'})
    private_market_get_stocks_symbol_securities_lending = privateMarketGetStocksSymbolSecuritiesLending = Entry('stocks/{symbol}/securities-lending', ['private', 'market'], 'GET', {'cost': 1, 'bucket': 'stock_trading_trend'})
    private_account_get_holdings = privateAccountGetHoldings = Entry('holdings', ['private', 'account'], 'GET', {'cost': 1, 'bucket': 'asset'})
    private_account_get_buying_power = privateAccountGetBuyingPower = Entry('buying-power', ['private', 'account'], 'GET', {'cost': 1, 'bucket': 'order_info', 'peak': True})
    private_account_get_commissions = privateAccountGetCommissions = Entry('commissions', ['private', 'account'], 'GET', {'cost': 1, 'bucket': 'order_info', 'peak': True})
    private_account_get_sellable_quantity = privateAccountGetSellableQuantity = Entry('sellable-quantity', ['private', 'account'], 'GET', {'cost': 1, 'bucket': 'order_info', 'peak': True})
    private_account_get_orders = privateAccountGetOrders = Entry('orders', ['private', 'account'], 'GET', {'cost': 1, 'bucket': 'order_history'})
    private_account_get_orders_orderid = privateAccountGetOrdersOrderId = Entry('orders/{orderId}', ['private', 'account'], 'GET', {'cost': 1, 'bucket': 'order_history'})
    private_account_get_conditional_orders = privateAccountGetConditionalOrders = Entry('conditional-orders', ['private', 'account'], 'GET', {'cost': 1, 'bucket': 'conditional_order_history'})
    private_account_get_conditional_orders_conditionalorderid = privateAccountGetConditionalOrdersConditionalOrderId = Entry('conditional-orders/{conditionalOrderId}', ['private', 'account'], 'GET', {'cost': 1, 'bucket': 'conditional_order_history'})
    private_account_post_orders = privateAccountPostOrders = Entry('orders', ['private', 'account'], 'POST', {'cost': 1, 'bucket': 'order', 'order': True})
    private_account_post_orders_orderid_cancel = privateAccountPostOrdersOrderIdCancel = Entry('orders/{orderId}/cancel', ['private', 'account'], 'POST', {'cost': 1, 'bucket': 'order', 'order': True})
    private_account_post_orders_orderid_modify = privateAccountPostOrdersOrderIdModify = Entry('orders/{orderId}/modify', ['private', 'account'], 'POST', {'cost': 1, 'bucket': 'order', 'order': True})
    private_account_post_conditional_orders = privateAccountPostConditionalOrders = Entry('conditional-orders', ['private', 'account'], 'POST', {'cost': 1, 'bucket': 'conditional_order', 'order': True})
    private_account_post_conditional_orders_conditionalorderid_modify = privateAccountPostConditionalOrdersConditionalOrderIdModify = Entry('conditional-orders/{conditionalOrderId}/modify', ['private', 'account'], 'POST', {'cost': 1, 'bucket': 'conditional_order', 'order': True})
    private_account_delete_conditional_orders_conditionalorderid = privateAccountDeleteConditionalOrdersConditionalOrderId = Entry('conditional-orders/{conditionalOrderId}', ['private', 'account'], 'DELETE', {'cost': 1, 'bucket': 'conditional_order', 'order': True})
